# Generated by Django 4.2.2 on 2023-06-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatars_default/avatar.png', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
